added real time updates for updated tasks

diff --git a/Backend/CCFinal/Dockerfile b/Backend/CCFinal/Dockerfile
--- a/Backend/CCFinal/Dockerfile
+++ b/Backend/CCFinal/Dockerfile
@@ -19,9 +19,9 @@ FROM build AS publish
 RUN dotnet publish "CCFinal.csproj" -c Release -o /app/publish --no-restore #/p:UseAppHost=false
 
 FROM base AS final
-RUN apt update
-RUN apt install --yes curl
-HEALTHCHECK CMD curl --fail http://localhost/healthcheck | grep -E '^{\"status\":\"Healthy\",' || exit 1
+#RUN apt update
+#RUN apt install --yes curl
+#HEALTHCHECK CMD curl --fail http://localhost/healthcheck | grep -E '^{\"status\":\"Healthy\",' || exit 1
 WORKDIR /app
 COPY --from=publish /app/publish .
 ENTRYPOINT ["dotnet", "CCFinal.dll", "--urls", "http://0.0.0.0:80"]
